### ISSUE TITLE
録音が機能していない

### ISSUE THREAD

**Issue by xtone-tnakagawa** [xtone-tnakagawa/mix-record-sounds-ios-sample#1]
アプリで録音ができていない。

デバッグで見ると「Recode」を押した後、
https://github.com/xtone-tnakagawa/mix-record-sounds-ios-sample/blob/24d8ed1c00da12735f807903b321c91f06d6c382/AudioTest/Audio/AudioService.swift#L44
ここでqueueが作られているようだが

https://github.com/xtone-tnakagawa/mix-record-sounds-ios-sample/blob/24d8ed1c00da12735f807903b321c91f06d6c382/AudioTest/Audio/AudioService.swift#L10
callbackであるこのメソッドは呼ばれていない模様（＝ブレークポイントを設定しても止まらない）
そのため、本来入ってくるはずの録音データがバッファにコピーされず、音声データが0バイトになっている。

**Comment by 0h-takaya** [comment]
一つ方法として、obj-cの情報が多いようなので
一旦obj-cで書いて、動作が確認できたらswiftに変換する。
ということをしてみてもよいと思います。

**Comment by xtone-tnakagawa** [comment]
確かにそれも有効な手段ですね。検討してみます。

**Comment by xtone-tnakagawa** [comment]
自己解決しました。処理の不足が原因です。

AudioQueueServiceを利用した録音機能は、以下の手順を踏みます。

1. `AudioQueueNewInput` でAudioFormatとCallbackを指定
( return `AudioQueueRef`)
2. `AudioQueueAllocateBuffer` で`AudioQueueRef`で管理するbuffer（Array）を指定  
( 録音されたデータは この buffer に書き込まれ、bufferがいっぱいになるとCallbackが呼ばれる )
3. `AudioQueueEnqueueBuffer` で `AudioQueueRef` のbufferを末尾に追加していく処理を追加
4. `AudioQueueRef`を指定して、キュー処理をスタートする

このうち、2. 3. の処理が抜けており、追加したところ正常に動きました。

参考URL：https://qiita.com/a_jike/items/68dd13879f9df5b2b7a2
